compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmMinimalAgeGate: 4320 # 3 days

npmPreapprovedPackages:
  - "@lightsparkdev/*"

yarnPath: .yarn/releases/yarn-4.13.0.cjs
