/**
 * Auto-generated by scripts/extract-icons.mjs — do not edit.
 *
 * To add or update icons, edit the SECTIONS config in that script
 * and run: yarn icons:extract
 */

// Arrows & Navigation
import { IconArrow } from "./icons/IconArrow";
import { IconArrowBoxRight } from "./icons/IconArrowBoxRight";
import { IconArrowDown } from "./icons/IconArrowDown";
import { IconArrowDownLeft } from "./icons/IconArrowDownLeft";
import { IconArrowDownRight } from "./icons/IconArrowDownRight";
import { IconArrowDownSquare } from "./icons/IconArrowDownSquare";
import { IconArrowDownWall } from "./icons/IconArrowDownWall";
import { IconArrowInbox } from "./icons/IconArrowInbox";
import { IconArrowLeft } from "./icons/IconArrowLeft";
import { IconArrowLeftSquare } from "./icons/IconArrowLeftSquare";
import { IconArrowLoopDownLeft } from "./icons/IconArrowLoopDownLeft";
import { IconArrowOutOfBox } from "./icons/IconArrowOutOfBox";
import { IconArrowRight } from "./icons/IconArrowRight";
import { IconArrowRightSquare } from "./icons/IconArrowRightSquare";
import { IconArrowUp } from "./icons/IconArrowUp";
import { IconArrowUpLeft } from "./icons/IconArrowUpLeft";
import { IconArrowUpRight } from "./icons/IconArrowUpRight";
import { IconArrowUpSquare } from "./icons/IconArrowUpSquare";
import { IconArrowUpWall } from "./icons/IconArrowUpWall";
import { IconArrowsRepeat } from "./icons/IconArrowsRepeat";
import { IconArrowsRepeatCircle } from "./icons/IconArrowsRepeatCircle";
import { IconRedirectArrow } from "./icons/IconRedirectArrow";
import { IconRotate360Left } from "./icons/IconRotate360Left";
import { IconRotate360Right } from "./icons/IconRotate360Right";

// Chevrons
import { IconChevronBottom } from "./icons/IconChevronBottom";
import { IconChevronDownSmall } from "./icons/IconChevronDownSmall";
import { IconChevronGrabberVertical } from "./icons/IconChevronGrabberVertical";
import { IconChevronLeft } from "./icons/IconChevronLeft";
import { IconChevronLeftSmall } from "./icons/IconChevronLeftSmall";
import { IconChevronRight } from "./icons/IconChevronRight";
import { IconChevronRightSmall } from "./icons/IconChevronRightSmall";
import { IconChevronTop } from "./icons/IconChevronTop";
import { IconChevronTopSmall } from "./icons/IconChevronTopSmall";

// Actions & UI
import { IconAdjustPhoto } from "./icons/IconAdjustPhoto";
import { IconAt } from "./icons/IconAt";
import { IconAutoCrop } from "./icons/IconAutoCrop";
import { IconBank } from "./icons/IconBank";
import { IconBarsThree2 } from "./icons/IconBarsThree2";
import { IconBell } from "./icons/IconBell";
import { IconBellOff } from "./icons/IconBellOff";
import { IconBlackpoint } from "./icons/IconBlackpoint";
import { IconBrackets1 } from "./icons/IconBrackets1";
import { IconBrokenHeart } from "./icons/IconBrokenHeart";
import { IconBrowserTabs } from "./icons/IconBrowserTabs";
import { IconBubble3 } from "./icons/IconBubble3";
import { IconBubbleWideSparkle } from "./icons/IconBubbleWideSparkle";
import { IconBuildings } from "./icons/IconBuildings";
import { IconCalendarDays } from "./icons/IconCalendarDays";
import { IconCheckmark2 } from "./icons/IconCheckmark2";
import { IconCheckmark2Small } from "./icons/IconCheckmark2Small";
import { IconCircleCheck } from "./icons/IconCircleCheck";
import { IconCircleCheckFilled } from "./icons/IconCircleCheckFilled";
import { IconCircleInfo } from "./icons/IconCircleInfo";
import { IconCircleInfoFilled } from "./icons/IconCircleInfoFilled";
import { IconCirclePlus } from "./icons/IconCirclePlus";
import { IconCircleQuestionmark } from "./icons/IconCircleQuestionmark";
import { IconCircleX } from "./icons/IconCircleX";
import { IconClipboard2 } from "./icons/IconClipboard2";
import { IconClipboard2Sparkle } from "./icons/IconClipboard2Sparkle";
import { IconClock } from "./icons/IconClock";
import { IconCmdBox } from "./icons/IconCmdBox";
import { IconCoinsAdd } from "./icons/IconCoinsAdd";
import { IconCoinsAddFilled } from "./icons/IconCoinsAddFilled";
import { IconConnectors1 } from "./icons/IconConnectors1";
import { IconConnectors2 } from "./icons/IconConnectors2";
import { IconConsoleSparkle } from "./icons/IconConsoleSparkle";
import { IconCrossLarge } from "./icons/IconCrossLarge";
import { IconCrossMedium } from "./icons/IconCrossMedium";
import { IconCrossSmall } from "./icons/IconCrossSmall";
import { IconCryptoWallet } from "./icons/IconCryptoWallet";
import { IconDevices } from "./icons/IconDevices";
import { IconDiamondShine } from "./icons/IconDiamondShine";
import { IconDifferenceIgnored } from "./icons/IconDifferenceIgnored";
import { IconDifferenceModified } from "./icons/IconDifferenceModified";
import { IconDiscoBall } from "./icons/IconDiscoBall";
import { IconDotGrid1x3Horizontal } from "./icons/IconDotGrid1x3Horizontal";
import { IconDotGrid1x3HorizontalTight } from "./icons/IconDotGrid1x3HorizontalTight";
import { IconDotGrid1x3Vertical } from "./icons/IconDotGrid1x3Vertical";
import { IconDotGrid1x3VerticalTight } from "./icons/IconDotGrid1x3VerticalTight";
import { IconDotGrid2x3 } from "./icons/IconDotGrid2x3";
import { IconDotGrid3x3 } from "./icons/IconDotGrid3x3";
import { IconExclamationTriangle } from "./icons/IconExclamationTriangle";
import { IconExclamationTriangleFilled } from "./icons/IconExclamationTriangleFilled";
import { IconEyeOpen } from "./icons/IconEyeOpen";
import { IconEyeSlash } from "./icons/IconEyeSlash";
import { IconEyeSlash2 } from "./icons/IconEyeSlash2";
import { IconFileArrowLeftIn } from "./icons/IconFileArrowLeftIn";
import { IconFileArrowLeftOut } from "./icons/IconFileArrowLeftOut";
import { IconFileArrowRightOut } from "./icons/IconFileArrowRightOut";
import { IconFileBend } from "./icons/IconFileBend";
import { IconFilter2 } from "./icons/IconFilter2";
import { IconFingerPrint1 } from "./icons/IconFingerPrint1";
import { IconFolderAddRight } from "./icons/IconFolderAddRight";
import { IconForYou } from "./icons/IconForYou";
import { IconFormPyramide } from "./icons/IconFormPyramide";
import { IconFullScreen } from "./icons/IconFullScreen";
import { IconGlobe2 } from "./icons/IconGlobe2";
import { IconHeart2 } from "./icons/IconHeart2";
import { IconHeart2Filled } from "./icons/IconHeart2Filled";
import { IconHome } from "./icons/IconHome";
import { IconImport2 } from "./icons/IconImport2";
import { IconInitiatives } from "./icons/IconInitiatives";
import { IconInvite } from "./icons/IconInvite";
import { IconKey2 } from "./icons/IconKey2";
import { IconLayoutColumn } from "./icons/IconLayoutColumn";
import { IconLayoutLeft } from "./icons/IconLayoutLeft";
import { IconLayoutRight } from "./icons/IconLayoutRight";
import { IconListSparkle } from "./icons/IconListSparkle";
import { IconLiveActivity } from "./icons/IconLiveActivity";
import { IconLiveFull } from "./icons/IconLiveFull";
import { IconLoader } from "./icons/IconLoader";
import { IconLock } from "./icons/IconLock";
import { IconMagnifyingGlass2 } from "./icons/IconMagnifyingGlass2";
import { IconMinusLarge } from "./icons/IconMinusLarge";
import { IconMinusSmall } from "./icons/IconMinusSmall";
import { IconMoon } from "./icons/IconMoon";
import { IconMouse } from "./icons/IconMouse";
import { IconOffline } from "./icons/IconOffline";
import { IconOngoing } from "./icons/IconOngoing";
import { IconOngoingFilled } from "./icons/IconOngoingFilled";
import { IconPaperPlaneTopRight } from "./icons/IconPaperPlaneTopRight";
import { IconPaperPlaneTopRightFilled } from "./icons/IconPaperPlaneTopRightFilled";
import { IconPaperclip1 } from "./icons/IconPaperclip1";
import { IconPassport } from "./icons/IconPassport";
import { IconPassword } from "./icons/IconPassword";
import { IconPasswordStars } from "./icons/IconPasswordStars";
import { IconPencil } from "./icons/IconPencil";
import { IconPencil2 } from "./icons/IconPencil2";
import { IconPencil3 } from "./icons/IconPencil3";
import { IconPencilAi } from "./icons/IconPencilAi";
import { IconPeople2 } from "./icons/IconPeople2";
import { IconPeople2Filled } from "./icons/IconPeople2Filled";
import { IconPeopleAdd } from "./icons/IconPeopleAdd";
import { IconPeopleAddFilled } from "./icons/IconPeopleAddFilled";
import { IconPeopleCircle } from "./icons/IconPeopleCircle";
import { IconPeopleIdCard } from "./icons/IconPeopleIdCard";
import { IconPhone } from "./icons/IconPhone";
import { IconPhoneDynamicIsland } from "./icons/IconPhoneDynamicIsland";
import { IconPlusLarge } from "./icons/IconPlusLarge";
import { IconPlusSmall } from "./icons/IconPlusSmall";
import { IconPrompt } from "./icons/IconPrompt";
import { IconRandom } from "./icons/IconRandom";
import { IconRemix } from "./icons/IconRemix";
import { IconRemoveKeyframe } from "./icons/IconRemoveKeyframe";
import { IconRepeat } from "./icons/IconRepeat";
import { IconRescueRing } from "./icons/IconRescueRing";
import { IconRunShortcut } from "./icons/IconRunShortcut";
import { IconScanCode } from "./icons/IconScanCode";
import { IconSearchIntelligence } from "./icons/IconSearchIntelligence";
import { IconSearchlinesSparkle } from "./icons/IconSearchlinesSparkle";
import { IconSecretPhrase } from "./icons/IconSecretPhrase";
import { IconSettingsGear1 } from "./icons/IconSettingsGear1";
import { IconSettingsGear2 } from "./icons/IconSettingsGear2";
import { IconShield } from "./icons/IconShield";
import { IconShield2 } from "./icons/IconShield2";
import { IconShieldKeyhole } from "./icons/IconShieldKeyhole";
import { IconSidebarSimpleLeftWide } from "./icons/IconSidebarSimpleLeftWide";
import { IconSpacebar } from "./icons/IconSpacebar";
import { IconSquareArrowTopRight2 } from "./icons/IconSquareArrowTopRight2";
import { IconSquareBehindSquare1 } from "./icons/IconSquareBehindSquare1";
import { IconSquareBehindSquare6 } from "./icons/IconSquareBehindSquare6";
import { IconSquareInfo } from "./icons/IconSquareInfo";
import { IconSquarePlus } from "./icons/IconSquarePlus";
import { IconSticker } from "./icons/IconSticker";
import { IconStop } from "./icons/IconStop";
import { IconStopCircle } from "./icons/IconStopCircle";
import { IconSun } from "./icons/IconSun";
import { IconTag } from "./icons/IconTag";
import { IconTarget } from "./icons/IconTarget";
import { IconTelescope } from "./icons/IconTelescope";
import { IconTextToSpeach } from "./icons/IconTextToSpeach";
import { IconTextareaDrag } from "./icons/IconTextareaDrag";
import { IconThumbDownCurved } from "./icons/IconThumbDownCurved";
import { IconThumbUpCurved } from "./icons/IconThumbUpCurved";
import { IconTimeFlies } from "./icons/IconTimeFlies";
import { IconTimeslot } from "./icons/IconTimeslot";
import { IconToggle } from "./icons/IconToggle";
import { IconTrashCanSimple } from "./icons/IconTrashCanSimple";
import { IconTrashRounded } from "./icons/IconTrashRounded";
import { IconUnblur } from "./icons/IconUnblur";
import { IconUsbC } from "./icons/IconUsbC";
import { IconVariables } from "./icons/IconVariables";
import { IconWallet1 } from "./icons/IconWallet1";
import { IconWallet3 } from "./icons/IconWallet3";
import { IconWeb3 } from "./icons/IconWeb3";
import { IconWindowSparkle } from "./icons/IconWindowSparkle";
import { IconWreathSimple } from "./icons/IconWreathSimple";

// AI & Sparkle
import { IconAgenticCoding } from "./icons/IconAgenticCoding";
import { IconImagineAi } from "./icons/IconImagineAi";
import { IconVibeCoding2 } from "./icons/IconVibeCoding2";
import { IconVisualIntelligence } from "./icons/IconVisualIntelligence";

// Voice
import { IconVoiceHigh } from "./icons/IconVoiceHigh";
import { IconVoiceLow } from "./icons/IconVoiceLow";
import { IconVoiceMid } from "./icons/IconVoiceMid";
import { IconVoiceRecord } from "./icons/IconVoiceRecord";
import { IconVoiceSettings } from "./icons/IconVoiceSettings";
import { IconVoiceSparkle } from "./icons/IconVoiceSparkle";

// User & People
import { IconPeople } from "./icons/IconPeople";
import { IconUserAddRight } from "./icons/IconUserAddRight";
import { IconUserAdded } from "./icons/IconUserAdded";
import { IconUserBlock } from "./icons/IconUserBlock";
import { IconUserDuo } from "./icons/IconUserDuo";
import { IconUserEdit } from "./icons/IconUserEdit";
import { IconUserGroup } from "./icons/IconUserGroup";
import { IconUserRemove } from "./icons/IconUserRemove";
import { IconUserRemoveRight } from "./icons/IconUserRemoveRight";
import { IconUserSettings } from "./icons/IconUserSettings";

// Brands & Logos
import { IconAntigravity } from "./icons/IconAntigravity";
import { IconApple } from "./icons/IconApple";
import { IconBitcoinLogo } from "./icons/IconBitcoinLogo";
import { IconClaudeai } from "./icons/IconClaudeai";
import { IconCursor } from "./icons/IconCursor";
import { IconEuropeanUnion } from "./icons/IconEuropeanUnion";
import { IconGemini } from "./icons/IconGemini";
import { IconGithub } from "./icons/IconGithub";
import { IconGrok } from "./icons/IconGrok";
import { IconIsoOrg } from "./icons/IconIsoOrg";
import { IconLinear } from "./icons/IconLinear";
import { IconLinkedin } from "./icons/IconLinkedin";
import { IconNotion } from "./icons/IconNotion";
import { IconOpenai } from "./icons/IconOpenai";
import { IconSlack } from "./icons/IconSlack";
import { IconSupabase } from "./icons/IconSupabase";
import { IconTwitter } from "./icons/IconTwitter";
import { IconV0 } from "./icons/IconV0";
import { IconVercel } from "./icons/IconVercel";

const IconChevronDown = IconChevronDownSmall;

export const ICON_REGISTRY = {
  // Arrows & Navigation
  IconArrow,
  IconArrowBoxRight,
  IconArrowDown,
  IconArrowDownLeft,
  IconArrowDownRight,
  IconArrowDownSquare,
  IconArrowDownWall,
  IconArrowInbox,
  IconArrowLeft,
  IconArrowLeftSquare,
  IconArrowLoopDownLeft,
  IconArrowOutOfBox,
  IconArrowRight,
  IconArrowRightSquare,
  IconArrowUp,
  IconArrowUpLeft,
  IconArrowUpRight,
  IconArrowUpSquare,
  IconArrowUpWall,
  IconArrowsRepeat,
  IconArrowsRepeatCircle,
  IconRedirectArrow,
  IconRotate360Left,
  IconRotate360Right,

  // Chevrons
  IconChevronBottom,
  IconChevronDown,
  IconChevronDownSmall,
  IconChevronGrabberVertical,
  IconChevronLeft,
  IconChevronLeftSmall,
  IconChevronRight,
  IconChevronRightSmall,
  IconChevronTop,
  IconChevronTopSmall,

  // Actions & UI
  IconAdjustPhoto,
  IconAt,
  IconAutoCrop,
  IconBank,
  IconBarsThree2,
  IconBell,
  IconBellOff,
  IconBlackpoint,
  IconBrackets1,
  IconBrokenHeart,
  IconBrowserTabs,
  IconBubble3,
  IconBubbleWideSparkle,
  IconBuildings,
  IconCalendarDays,
  IconCheckmark2,
  IconCheckmark2Small,
  IconCircleCheck,
  IconCircleCheckFilled,
  IconCircleInfo,
  IconCircleInfoFilled,
  IconCirclePlus,
  IconCircleQuestionmark,
  IconCircleX,
  IconClipboard2,
  IconClipboard2Sparkle,
  IconClock,
  IconCmdBox,
  IconCoinsAdd,
  IconCoinsAddFilled,
  IconConnectors1,
  IconConnectors2,
  IconConsoleSparkle,
  IconCrossLarge,
  IconCrossMedium,
  IconCrossSmall,
  IconCryptoWallet,
  IconDevices,
  IconDiamondShine,
  IconDifferenceIgnored,
  IconDifferenceModified,
  IconDiscoBall,
  IconDotGrid1x3Horizontal,
  IconDotGrid1x3HorizontalTight,
  IconDotGrid1x3Vertical,
  IconDotGrid1x3VerticalTight,
  IconDotGrid2x3,
  IconDotGrid3x3,
  IconExclamationTriangle,
  IconExclamationTriangleFilled,
  IconEyeOpen,
  IconEyeSlash,
  IconEyeSlash2,
  IconFileArrowLeftIn,
  IconFileArrowLeftOut,
  IconFileArrowRightOut,
  IconFileBend,
  IconFilter2,
  IconFingerPrint1,
  IconFolderAddRight,
  IconForYou,
  IconFormPyramide,
  IconFullScreen,
  IconGlobe2,
  IconHeart2,
  IconHeart2Filled,
  IconHome,
  IconImport2,
  IconInitiatives,
  IconInvite,
  IconKey2,
  IconLayoutColumn,
  IconLayoutLeft,
  IconLayoutRight,
  IconListSparkle,
  IconLiveActivity,
  IconLiveFull,
  IconLoader,
  IconLock,
  IconMagnifyingGlass2,
  IconMinusLarge,
  IconMinusSmall,
  IconMoon,
  IconMouse,
  IconOffline,
  IconOngoing,
  IconOngoingFilled,
  IconPaperPlaneTopRight,
  IconPaperPlaneTopRightFilled,
  IconPaperclip1,
  IconPassport,
  IconPassword,
  IconPasswordStars,
  IconPencil,
  IconPencil2,
  IconPencil3,
  IconPencilAi,
  IconPeople2,
  IconPeople2Filled,
  IconPeopleAdd,
  IconPeopleAddFilled,
  IconPeopleCircle,
  IconPeopleIdCard,
  IconPhone,
  IconPhoneDynamicIsland,
  IconPlusLarge,
  IconPlusSmall,
  IconPrompt,
  IconRandom,
  IconRemix,
  IconRemoveKeyframe,
  IconRepeat,
  IconRescueRing,
  IconRunShortcut,
  IconScanCode,
  IconSearchIntelligence,
  IconSearchlinesSparkle,
  IconSecretPhrase,
  IconSettingsGear1,
  IconSettingsGear2,
  IconShield,
  IconShield2,
  IconShieldKeyhole,
  IconSidebarSimpleLeftWide,
  IconSpacebar,
  IconSquareArrowTopRight2,
  IconSquareBehindSquare1,
  IconSquareBehindSquare6,
  IconSquareInfo,
  IconSquarePlus,
  IconSticker,
  IconStop,
  IconStopCircle,
  IconSun,
  IconTag,
  IconTarget,
  IconTelescope,
  IconTextToSpeach,
  IconTextareaDrag,
  IconThumbDownCurved,
  IconThumbUpCurved,
  IconTimeFlies,
  IconTimeslot,
  IconToggle,
  IconTrashCanSimple,
  IconTrashRounded,
  IconUnblur,
  IconUsbC,
  IconVariables,
  IconWallet1,
  IconWallet3,
  IconWeb3,
  IconWindowSparkle,
  IconWreathSimple,

  // AI & Sparkle
  IconAgenticCoding,
  IconImagineAi,
  IconVibeCoding2,
  IconVisualIntelligence,

  // Voice
  IconVoiceHigh,
  IconVoiceLow,
  IconVoiceMid,
  IconVoiceRecord,
  IconVoiceSettings,
  IconVoiceSparkle,

  // User & People
  IconPeople,
  IconUserAddRight,
  IconUserAdded,
  IconUserBlock,
  IconUserDuo,
  IconUserEdit,
  IconUserGroup,
  IconUserRemove,
  IconUserRemoveRight,
  IconUserSettings,

  // Brands & Logos
  IconAntigravity,
  IconApple,
  IconBitcoinLogo,
  IconClaudeai,
  IconCursor,
  IconEuropeanUnion,
  IconGemini,
  IconGithub,
  IconGrok,
  IconIsoOrg,
  IconLinear,
  IconLinkedin,
  IconNotion,
  IconOpenai,
  IconSlack,
  IconSupabase,
  IconTwitter,
  IconV0,
  IconVercel,
} as const;

export type CentralIconName = keyof typeof ICON_REGISTRY;
