import {
  Root,
  Trigger,
  Portal,
  Positioner,
  Popup,
  Item,
  LinkItem,
  CheckboxItem,
  CheckboxItemIndicator,
  RadioGroup,
  RadioItem,
  RadioItemIndicator,
  Separator,
  Group,
  GroupLabel,
  SubmenuRoot,
  SubmenuTrigger,
  Arrow,
  Backdrop,
} from "./parts";

export {
  Root,
  Trigger,
  Portal,
  Positioner,
  Popup,
  Item,
  LinkItem,
  CheckboxItem,
  CheckboxItemIndicator,
  RadioGroup,
  RadioItem,
  RadioItemIndicator,
  Separator,
  Group,
  GroupLabel,
  SubmenuRoot,
  SubmenuTrigger,
  Arrow,
  Backdrop,
  type RootProps,
  type TriggerProps,
  type PortalProps,
  type PositionerProps,
  type PopupProps,
  type ItemProps,
  type LinkItemProps,
  type CheckboxItemProps,
  type CheckboxItemIndicatorProps,
  type RadioGroupProps,
  type RadioItemProps,
  type RadioItemIndicatorProps,
  type SeparatorProps,
  type GroupProps,
  type GroupLabelProps,
  type SubmenuRootProps,
  type SubmenuTriggerProps,
  type ArrowProps,
  type BackdropProps,
} from "./parts";

export const Menu = {
  Root,
  Trigger,
  Portal,
  Positioner,
  Popup,
  Item,
  LinkItem,
  CheckboxItem,
  CheckboxItemIndicator,
  RadioGroup,
  RadioItem,
  RadioItemIndicator,
  Separator,
  Group,
  GroupLabel,
  SubmenuRoot,
  SubmenuTrigger,
  Arrow,
  Backdrop,
};

export default Menu;
