import {
  useSidebar,
  Provider,
  Root,
  Trigger,
  Header,
  Content,
  Footer,
  Group,
  GroupLabel,
  Menu,
  Tree,
  Item,
  ExpandableItem,
  SubmenuItem,
  DrilldownItem,
  TreeItem,
  Separator,
} from "./parts";

export {
  useSidebar,
  Provider,
  Root,
  Trigger,
  Header,
  Content,
  Footer,
  Group,
  GroupLabel,
  Menu,
  Tree,
  Item,
  ExpandableItem,
  SubmenuItem,
  DrilldownItem,
  TreeItem,
  Separator,
} from "./parts";

export type {
  SidebarContextValue,
  ProviderProps,
  RootProps,
  TriggerProps,
  HeaderProps,
  ContentProps,
  FooterProps,
  GroupProps,
  GroupLabelProps,
  MenuProps,
  TreeProps,
  ItemProps,
  ExpandableItemProps,
  SubmenuItemProps,
  DrilldownItemProps,
  TreeItemProps,
  SeparatorProps,
} from "./parts";

export const Sidebar = {
  useSidebar,
  Provider,
  Root,
  Trigger,
  Header,
  Content,
  Footer,
  Group,
  GroupLabel,
  Menu,
  Tree,
  Item,
  ExpandableItem,
  SubmenuItem,
  DrilldownItem,
  TreeItem,
  Separator,
};

export type {
  ProviderProps as SidebarProviderProps,
  RootProps as SidebarRootProps,
  TriggerProps as SidebarTriggerProps,
  HeaderProps as SidebarHeaderProps,
  ContentProps as SidebarContentProps,
  FooterProps as SidebarFooterProps,
  GroupProps as SidebarGroupProps,
  GroupLabelProps as SidebarGroupLabelProps,
  MenuProps as SidebarMenuProps,
  TreeProps as SidebarTreeProps,
  ItemProps as SidebarItemProps,
  ExpandableItemProps as SidebarExpandableItemProps,
  SubmenuItemProps as SidebarSubmenuItemProps,
  DrilldownItemProps as SidebarDrilldownItemProps,
  TreeItemProps as SidebarTreeItemProps,
  SeparatorProps as SidebarSeparatorProps,
} from "./parts";
