export enum App {
  Lightspark = "Lightspark",
  UmaDocs = "UmaDocs",
}

const FONT_FAMILIES = {
  main: "Montserrat",
  code: "Monaco",
};

const LINE_HEIGHTS = {
  [App.UmaDocs]: {
    "5xl": "72px",
    "4xl": "60px",
    "3xl": "44px",
    "2xl": "40px",
    xl: "36px",
    lg: "32px",
    md: "28px",
    sm: "24px",
    xs: "20px",
    "2xs": "16px",
  },
  [App.Lightspark]: {
    "7xl": "72px",
    "6xl": "60px",
    "5xl": "44px",
    "4xl": "40px",
    "3xl": "36px",
    "2xl": "32px",
    xl: "28px",
    lg: "24px",
    md: "20px",
    sm: "18px",
    xs: "16px",
    "2xs": "14px",
  },
};

const FONT_WEIGHTS = {
  main: {
    Bold: 700,
    SemiBold: 600,
    Medium: 500,
  },
  code: {
    Bold: 700,
    Regular: 400,
  },
};

const FONT_SIZE = {
  [App.UmaDocs]: {
    "2xs": "11px",
    xs: "12px",
    sm: "14px",
    md: "16px",
    lg: "20px",
    xl: "24px",
    "2xl": "28px",
    "3xl": "32px",
    "4xl": "36px",
    "5xl": "48px",
    "6xl": "64px",
  },
  [App.Lightspark]: {
    "2xs": "10px",
    xs: "12px",
    sm: "14px",
    md: "16px",
    lg: "20px",
    xl: "24px",
    "2xl": "28px",
    "3xl": "32px",
    "4xl": "36px",
    "5xl": "48px",
    "6xl": "64px",
  },
};

const LETTER_SPACING = {
  [App.UmaDocs]: {
    tight: "-.02em",
    normal: "0",
    loose: ".1em",
  },
  [App.Lightspark]: {
    "tight-max": "-4%",
    "tight-high": "-3%",
    "tight-medium": "-2%",
    "tight-low": "-0.5%",
    normal: "0",
    "loose-max": "1.44px",
  },
};

const TEXT_CASE = {
  none: "none",
  uppercase: "uppercase",
};

const TEXT_DECORATION = {
  none: "none",
};

const PARAGRAPH_INDENT = {
  0: "0px",
};

const PARAGRAPH_SPACING = {
  default: "default",
  0: "0",
  16: "16px",
  40: "40px",
};

export interface FontFamilies {
  main: string;
  code: string;
}

interface Token {
  "font-family": string;
  "font-weight": string;
  "line-height": string;
  "font-size": string;
  "letter-spacing": string;
  "paragraph-spacing": string;
  "paragraph-indent": string;
  "text-case": string;
  "text-decoration": string;
}

export enum TokenSize {
  Large = "Large",
  Medium = "Medium",
  Small = "Small",
}

export const getTypography = (customFontFamilies?: FontFamilies) => {
  const fontFamilies = customFontFamilies ?? FONT_FAMILIES;
  return {
    fontFamilies,
    lineHeights: LINE_HEIGHTS,
    fontWeights: FONT_WEIGHTS,
    fontSize: FONT_SIZE,
    letterSpacing: LETTER_SPACING,
    textCase: TEXT_CASE,
    textDecoration: TEXT_DECORATION,
    paragraphIndent: PARAGRAPH_INDENT,
    paragraphSpacing: PARAGRAPH_SPACING,
    [App.Lightspark]: {
      Display: {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark]["7xl"]}`,
          "font-size": `${FONT_SIZE[App.Lightspark]["6xl"]}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-max"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark]["6xl"]}`,
          "font-size": `${FONT_SIZE[App.Lightspark]["5xl"]}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-max"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark]["5xl"]}`,
          "font-size": `${FONT_SIZE[App.Lightspark]["4xl"]}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-max"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      Headline: {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark]["4xl"]}`,
          "font-size": `${FONT_SIZE[App.Lightspark]["3xl"]}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-high"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark]["3xl"]}`,
          "font-size": `${FONT_SIZE[App.Lightspark]["2xl"]}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-high"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark]["2xl"]}`,
          "font-size": `${FONT_SIZE[App.Lightspark].xl}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-high"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      Title: {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].xl}`,
          "font-size": `${FONT_SIZE[App.Lightspark].lg}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-medium"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].lg}`,
          "font-size": `${FONT_SIZE[App.Lightspark].md}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-medium"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].md}`,
          "font-size": `${FONT_SIZE[App.Lightspark].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-medium"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      Body: {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Medium}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].xl}`,
          "font-size": `${FONT_SIZE[App.Lightspark].lg}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-low"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Medium}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].lg}`,
          "font-size": `${FONT_SIZE[App.Lightspark].md}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-low"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Medium}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].md}`,
          "font-size": `${FONT_SIZE[App.Lightspark].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-low"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      "Body Strong": {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].xl}`,
          "font-size": `${FONT_SIZE[App.Lightspark].lg}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-low"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].lg}`,
          "font-size": `${FONT_SIZE[App.Lightspark].md}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-low"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].md}`,
          "font-size": `${FONT_SIZE[App.Lightspark].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-low"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      Label: {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Medium}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].md}`,
          "font-size": `${FONT_SIZE[App.Lightspark].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-low"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Medium}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].xs}`,
          "font-size": `${FONT_SIZE[App.Lightspark].xs}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-low"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Medium}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark]["2xs"]}`,
          "font-size": `${FONT_SIZE[App.Lightspark]["2xs"]}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-low"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      "Label Moderate": {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.SemiBold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].md}`,
          "font-size": `${FONT_SIZE[App.Lightspark].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-low"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.SemiBold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].xs}`,
          "font-size": `${FONT_SIZE[App.Lightspark].xs}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-low"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.SemiBold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark]["2xs"]}`,
          "font-size": `${FONT_SIZE[App.Lightspark]["2xs"]}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-low"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      "Label Strong": {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].md}`,
          "font-size": `${FONT_SIZE[App.Lightspark].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-low"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].xs}`,
          "font-size": `${FONT_SIZE[App.Lightspark].xs}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-low"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark]["2xs"]}`,
          "font-size": `${FONT_SIZE[App.Lightspark]["2xs"]}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["tight-low"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      Overline: {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].lg}`,
          "font-size": `${FONT_SIZE[App.Lightspark].md}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["loose-max"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.uppercase}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].md}`,
          "font-size": `${FONT_SIZE[App.Lightspark].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["loose-max"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.uppercase}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].xs}`,
          "font-size": `${FONT_SIZE[App.Lightspark].xs}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark]["loose-max"]}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.uppercase}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      Code: {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.code}`,
          "font-weight": `${FONT_WEIGHTS.code.Regular}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].xl}`,
          "font-size": `${FONT_SIZE[App.Lightspark].lg}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.code}`,
          "font-weight": `${FONT_WEIGHTS.code.Regular}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].lg}`,
          "font-size": `${FONT_SIZE[App.Lightspark].md}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.code}`,
          "font-weight": `${FONT_WEIGHTS.code.Regular}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].md}`,
          "font-size": `${FONT_SIZE[App.Lightspark].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      "Code Strong": {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.code}`,
          "font-weight": `${FONT_WEIGHTS.code.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].lg}`,
          "font-size": `${FONT_SIZE[App.Lightspark].md}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.code}`,
          "font-weight": `${FONT_WEIGHTS.code.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].md}`,
          "font-size": `${FONT_SIZE[App.Lightspark].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.code}`,
          "font-weight": `${FONT_WEIGHTS.code.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.Lightspark].xs}`,
          "font-size": `${FONT_SIZE[App.Lightspark].xs}`,
          "letter-spacing": `${LETTER_SPACING[App.Lightspark].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[0]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
    },
    [App.UmaDocs]: {
      Display: {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs]["5xl"]}`,
          "font-size": `${FONT_SIZE[App.UmaDocs]["6xl"]}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].tight}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs]["4xl"]}`,
          "font-size": `${FONT_SIZE[App.UmaDocs]["5xl"]}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].tight}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs]["3xl"]}`,
          "font-size": `${FONT_SIZE[App.UmaDocs]["4xl"]}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].tight}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      Headline: {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs]["2xl"]}`,
          "font-size": `${FONT_SIZE[App.UmaDocs]["3xl"]}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].tight}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[16]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].xl}`,
          "font-size": `${FONT_SIZE[App.UmaDocs]["2xl"]}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].tight}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[16]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].lg}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].xl}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].tight}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING[16]}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      Title: {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].md}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].lg}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].sm}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].md}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].xs}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      Body: {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.SemiBold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].sm}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].md}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Medium}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].sm}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Medium}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].sm}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].xs}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      "Body Strong": {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].sm}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].md}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.SemiBold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].sm}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.SemiBold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].sm}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].xs}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      Label: {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.SemiBold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].xs}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.SemiBold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs]["2xs"]}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].xs}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.SemiBold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs]["2xs"]}`,
          "font-size": `${FONT_SIZE[App.UmaDocs]["2xs"]}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      "Label Moderate": {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].xs}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs]["2xs"]}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].xs}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs]["2xs"]}`,
          "font-size": `${FONT_SIZE[App.UmaDocs]["2xs"]}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      "Label Strong": {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].xs}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs]["2xs"]}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].xs}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs]["2xs"]}`,
          "font-size": `${FONT_SIZE[App.UmaDocs]["2xs"]}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      Overline: {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].sm}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].md}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].loose}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.uppercase}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].xs}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].loose}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.uppercase}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.main}`,
          "font-weight": `${FONT_WEIGHTS.main.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs]["2xs"]}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].xs}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].loose}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.uppercase}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      Code: {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.code}`,
          "font-weight": `${FONT_WEIGHTS.code.Regular}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].sm}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].md}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.code}`,
          "font-weight": `${FONT_WEIGHTS.code.Regular}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].sm}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.code}`,
          "font-weight": `${FONT_WEIGHTS.code.Regular}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].xs}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].xs}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
      "Code Strong": {
        [TokenSize.Large]: {
          "font-family": `${fontFamilies.code}`,
          "font-weight": `${FONT_WEIGHTS.code.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].sm}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].md}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Medium]: {
          "font-family": `${fontFamilies.code}`,
          "font-weight": `${FONT_WEIGHTS.code.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].sm}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].sm}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
        [TokenSize.Small]: {
          "font-family": `${fontFamilies.code}`,
          "font-weight": `${FONT_WEIGHTS.code.Bold}`,
          "line-height": `${LINE_HEIGHTS[App.UmaDocs].sm}`,
          "font-size": `${FONT_SIZE[App.UmaDocs].xs}`,
          "letter-spacing": `${LETTER_SPACING[App.UmaDocs].normal}`,
          "paragraph-spacing": `${PARAGRAPH_SPACING.default}`,
          "paragraph-indent": `${PARAGRAPH_INDENT[0]}`,
          "text-case": `${TEXT_CASE.none}`,
          "text-decoration": `${TEXT_DECORATION.none}`,
        },
      },
    },
  };
};

export const getTypographyString = (token: Token) => {
  return Object.entries(token)
    .map((entry) => {
      // Transform any non-css token properties into valid css.
      switch (entry[0]) {
        case "paragraph-spacing":
          return entry[1] === "default" ? "" : `margin-bottom: ${entry[1]};`;
        case "paragraph-indent":
          return `text-indent: ${entry[1]};`;
        case "text-case":
          return `text-transform: ${entry[1]};`;
        default:
          return `${entry[0]}: ${entry[1]};`;
      }
    })
    .join("");
};
